name: Deploy NodeJs Application to AWS EC2

on: push:
  branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Via SSH
        uses: aappleboy/ssh-deploy@v0.1.0
        with:
          host:${ secrets.SSH_HOST }
          username: root
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/Nodejs-application-deploy-github-action
            git pull 
            docker compose up -d --build
